/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    categories: Category;
    products: Product;
    orders: Order;
    customers: Customer;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      trelloDispatchOrder: TaskTrelloDispatchOrder;
      sendOrderConfirmationEmail: TaskSendOrderConfirmationEmail;
      catalogImportRows: TaskCatalogImportRows;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      'order-created': WorkflowOrderCreated;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * La URL pública de la tienda se creará de inmediato en: https://flow.martes.app/[slug]. No puede ser una palabra reservada del sistema (admin, api, demo, templates...).
   */
  slug: string;
  /**
   * Elige si la tienda usa la plantilla del Plan Básico o una de las plantillas Premium especializadas.
   */
  theme?:
    | (
        | 'basic-banner'
        | 'food-delivery'
        | 'fashion-boutique'
        | 'moto-parts'
        | 'hardware-store'
        | 'b2b-matrix'
        | 'editorial'
        | 'fluid-pwa'
        | 'vercel-commerce'
      )
    | null;
  /**
   * Incluir código de país sin el signo + (ej: 34600111222 o 584121234567)
   */
  whatsappPhone: string;
  emailConfig?: {
    enabled?: boolean | null;
    /**
     * Se guarda oculta (write-only): pégala para usarla o pégala de nuevo para rotarla. Si el comercio coloca su propia clave de Resend, usará su cuenta y su cuota individual; si se deja vacío, usa la clave global del sistema.
     */
    resendApiKey?: string | null;
    /**
     * Debe estar verificado en la cuenta de Resend utilizada. Debe ser único: ningún otro comercio puede usar el mismo correo remitente.
     */
    fromEmail?: string | null;
    /**
     * Recibirá una copia de cada orden generada con el PDF de nota de entrega adjunto.
     */
    notificationEmail?: string | null;
    emailSubject?: string | null;
  };
  trelloConfig?: {
    enabled?: boolean | null;
    /**
     * Ej: Aura Moda (Espacio de trabajo dedicado para esta tienda)
     */
    workspaceName?: string | null;
    /**
     * Ej: Pedidos Aura Moda
     */
    boardName?: string | null;
    /**
     * URL directa para abrir el tablero desde el Dashboard o celular
     */
    boardUrl?: string | null;
    /**
     * ID de 24 caracteres alfanuméricos de la columna "Pendiente" del tablero en Trello
     */
    listId?: string | null;
    /**
     * Se guarda oculta (write-only): pégala para usarla o pégala de nuevo para rotarla. Requiere también su Token propio (ambos o ninguno). Si se deja vacío, usa la cuenta maestra global del sistema.
     */
    apiKey?: string | null;
    /**
     * Se guarda oculto (write-only), igual que la API Key propia. Ambos campos deben venir de la misma cuenta de Trello del comercio.
     */
    token?: string | null;
  };
  branding?: {
    logo?: (number | null) | Media;
    currency?: ('USD' | 'EUR' | 'MXN' | 'COP') | null;
    showVES?: boolean | null;
    /**
     * Si se deja vacío o en 0, el sistema toma automáticamente la tasa en tiempo real de Binance P2P.
     */
    exchangeRateVES?: number | null;
    primaryColor?: string | null;
    welcomeMessage?: string | null;
  };
  pickupConfig?: {
    enabled?: boolean | null;
    locationAddress?: string | null;
    schedule?: string | null;
    estimatedTime?: string | null;
    instructions?: string | null;
  };
  paymentMethodsConfig?: {
    pagoMovil?: {
      enabled?: boolean | null;
      bank?: string | null;
      phone?: string | null;
      idDoc?: string | null;
      accountHolder?: string | null;
    };
    zelle?: {
      enabled?: boolean | null;
      email?: string | null;
      accountHolder?: string | null;
    };
    binance?: {
      enabled?: boolean | null;
      payId?: string | null;
      nickname?: string | null;
    };
    zinli?: {
      enabled?: boolean | null;
      email?: string | null;
      accountHolder?: string | null;
    };
    banescoPanama?: {
      enabled?: boolean | null;
      accountNumber?: string | null;
      accountHolder?: string | null;
      accountType?: string | null;
    };
    cash?: {
      enabled?: boolean | null;
      instructions?: string | null;
    };
    pos?: {
      enabled?: boolean | null;
      instructions?: string | null;
    };
  };
  deliveryConfig?: {
    /**
     * Costo fijo de envío que se suma automáticamente al pedido cuando el cliente selecciona Delivery. Si se coloca 0, el delivery no tiene costo adicional.
     */
    fixedPrice?: number | null;
    /**
     * Aparece en el checkout y en el mensaje de confirmación.
     */
    estimatedTime?: string | null;
    zones?:
      | {
          name: string;
          priceDelivery?: number | null;
          estimatedTime?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Descripción breve de la imagen para accesibilidad y SEO. Ej: "Pizza margherita con albahaca fresca"
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'super-admin' | 'tenant-admin';
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Pega una o varias URLs de imagen de hosts permitidos (Unsplash, Cloudflare R2, martes.app, Google, Cloudinary, Imgur, Shopify, Supabase, Vercel). Puedes separar varias URLs por coma o añadirlas fila por fila. La primera es la foto principal.
   */
  imageUrls?: string[] | null;
  title: string;
  sku: string;
  price: number;
  description?: string | null;
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  category?: (number | null) | Category;
  stockStatus?: ('in_stock' | 'out_of_stock') | null;
  trackStock?: boolean | null;
  stockQuantity?: number | null;
  featured?: boolean | null;
  variants?:
    | {
        name: string;
        sku?: string | null;
        price: number;
        stockQuantity?: number | null;
        stockStatus?: ('in_stock' | 'out_of_stock') | null;
        id?: string | null;
      }[]
    | null;
  modifiers?:
    | {
        groupName: string;
        required?: boolean | null;
        options?:
          | {
              name: string;
              priceDelta?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  tenant?: (number | null) | Tenant;
  orderNumber: string;
  /**
   * Tasa Bs/USD con la que se calculó este pedido. Se congela aquí para conciliación, aunque la tasa del tenant cambie después.
   */
  exchangeRateVES?: number | null;
  status: 'pending' | 'confirmed' | 'preparing' | 'in_delivery' | 'delivered' | 'cancelled';
  customer: {
    name: string;
    phone: string;
    email: string;
    address?: string | null;
    paymentMethod?: string | null;
    notes?: string | null;
  };
  items: {
    sku?: string | null;
    title: string;
    price: number;
    quantity: number;
    subtotal?: number | null;
    id?: string | null;
  }[];
  totalAmount: number;
  currency?: string | null;
  deliveryType?: ('delivery' | 'pickup') | null;
  deliveryDetails?: {
    municipality?: string | null;
    residenceZone?: string | null;
    buildingHouse?: string | null;
    referencePoint?: string | null;
  };
  paymentDetails?: {
    methodKey?: ('pago_movil' | 'zelle' | 'binance' | 'zinli' | 'banesco_panama' | 'cash' | 'pos') | null;
    referenceNumber?: string | null;
    issuingBank?: string | null;
    issuingPhone?: string | null;
    senderName?: string | null;
    senderEmail?: string | null;
    binanceSenderId?: string | null;
    paymentStatus?: ('pending_verification' | 'verified' | 'rejected') | null;
  };
  /**
   * Indica si este pedido ya fue contado en el CRM del cliente (totalOrders/totalSpent). Los pedidos creados fuera del checkout quedan en false.
   */
  crmCounted?: boolean | null;
  trelloCardUrl?: string | null;
  /**
   * Indica si el correo de confirmación fue enviado exitosamente al cliente para evitar duplicados en reintentos.
   */
  emailConfirmationSent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  phone: string;
  email?: string | null;
  tag?: ('nuevo' | 'frecuente' | 'vip' | 'inactivo') | null;
  totalOrders?: number | null;
  totalSpent?: number | null;
  lastOrderAt?: string | null;
  savedAddresses?:
    | {
        label?: string | null;
        municipality?: string | null;
        residenceZone?: string | null;
        buildingHouse?: string | null;
        referencePoint?: string | null;
        address?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  /**
   * Registro de todos los pedidos del cliente para análisis de patrones y retención.
   */
  purchaseHistory?:
    | {
        orderId?: (number | null) | Order;
        amount?: number | null;
        date?: string | null;
        /**
         * Lista de productos comprados en este pedido.
         */
        itemsSummary?: string | null;
        deliveryType?: ('delivery' | 'pickup') | null;
        id?: string | null;
      }[]
    | null;
  preferences?: {
    /**
     * Método de pago que el cliente usa más frecuentemente.
     */
    preferredPaymentMethod?: string | null;
    preferredDeliveryType?: ('delivery' | 'pickup' | 'none') | null;
    /**
     * Promedio de gasto por pedido (calculado automáticamente).
     */
    averageOrderValue?: number | null;
    preferredCategories?:
      | {
          category?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'trelloDispatchOrder' | 'sendOrderConfirmationEmail' | 'catalogImportRows';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?: 'order-created' | null;
  taskSlug?: ('inline' | 'trelloDispatchOrder' | 'sendOrderConfirmationEmail' | 'catalogImportRows') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  theme?: T;
  whatsappPhone?: T;
  emailConfig?:
    | T
    | {
        enabled?: T;
        resendApiKey?: T;
        fromEmail?: T;
        notificationEmail?: T;
        emailSubject?: T;
      };
  trelloConfig?:
    | T
    | {
        enabled?: T;
        workspaceName?: T;
        boardName?: T;
        boardUrl?: T;
        listId?: T;
        apiKey?: T;
        token?: T;
      };
  branding?:
    | T
    | {
        logo?: T;
        currency?: T;
        showVES?: T;
        exchangeRateVES?: T;
        primaryColor?: T;
        welcomeMessage?: T;
      };
  pickupConfig?:
    | T
    | {
        enabled?: T;
        locationAddress?: T;
        schedule?: T;
        estimatedTime?: T;
        instructions?: T;
      };
  paymentMethodsConfig?:
    | T
    | {
        pagoMovil?:
          | T
          | {
              enabled?: T;
              bank?: T;
              phone?: T;
              idDoc?: T;
              accountHolder?: T;
            };
        zelle?:
          | T
          | {
              enabled?: T;
              email?: T;
              accountHolder?: T;
            };
        binance?:
          | T
          | {
              enabled?: T;
              payId?: T;
              nickname?: T;
            };
        zinli?:
          | T
          | {
              enabled?: T;
              email?: T;
              accountHolder?: T;
            };
        banescoPanama?:
          | T
          | {
              enabled?: T;
              accountNumber?: T;
              accountHolder?: T;
              accountType?: T;
            };
        cash?:
          | T
          | {
              enabled?: T;
              instructions?: T;
            };
        pos?:
          | T
          | {
              enabled?: T;
              instructions?: T;
            };
      };
  deliveryConfig?:
    | T
    | {
        fixedPrice?: T;
        estimatedTime?: T;
        zones?:
          | T
          | {
              name?: T;
              priceDelivery?: T;
              estimatedTime?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  imageUrls?: T;
  title?: T;
  sku?: T;
  price?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  category?: T;
  stockStatus?: T;
  trackStock?: T;
  stockQuantity?: T;
  featured?: T;
  variants?:
    | T
    | {
        name?: T;
        sku?: T;
        price?: T;
        stockQuantity?: T;
        stockStatus?: T;
        id?: T;
      };
  modifiers?:
    | T
    | {
        groupName?: T;
        required?: T;
        options?:
          | T
          | {
              name?: T;
              priceDelta?: T;
              id?: T;
            };
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  tenant?: T;
  orderNumber?: T;
  exchangeRateVES?: T;
  status?: T;
  customer?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        address?: T;
        paymentMethod?: T;
        notes?: T;
      };
  items?:
    | T
    | {
        sku?: T;
        title?: T;
        price?: T;
        quantity?: T;
        subtotal?: T;
        id?: T;
      };
  totalAmount?: T;
  currency?: T;
  deliveryType?: T;
  deliveryDetails?:
    | T
    | {
        municipality?: T;
        residenceZone?: T;
        buildingHouse?: T;
        referencePoint?: T;
      };
  paymentDetails?:
    | T
    | {
        methodKey?: T;
        referenceNumber?: T;
        issuingBank?: T;
        issuingPhone?: T;
        senderName?: T;
        senderEmail?: T;
        binanceSenderId?: T;
        paymentStatus?: T;
      };
  crmCounted?: T;
  trelloCardUrl?: T;
  emailConfirmationSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  phone?: T;
  email?: T;
  tag?: T;
  totalOrders?: T;
  totalSpent?: T;
  lastOrderAt?: T;
  savedAddresses?:
    | T
    | {
        label?: T;
        municipality?: T;
        residenceZone?: T;
        buildingHouse?: T;
        referencePoint?: T;
        address?: T;
        id?: T;
      };
  notes?: T;
  purchaseHistory?:
    | T
    | {
        orderId?: T;
        amount?: T;
        date?: T;
        itemsSummary?: T;
        deliveryType?: T;
        id?: T;
      };
  preferences?:
    | T
    | {
        preferredPaymentMethod?: T;
        preferredDeliveryType?: T;
        averageOrderValue?: T;
        preferredCategories?:
          | T
          | {
              category?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskTrelloDispatchOrder".
 */
export interface TaskTrelloDispatchOrder {
  input: {
    orderId: number;
  };
  output: {
    skipped?: boolean | null;
    cardId?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendOrderConfirmationEmail".
 */
export interface TaskSendOrderConfirmationEmail {
  input: {
    orderId: number;
  };
  output: {
    skipped?: boolean | null;
    sent?: boolean | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCatalogImportRows".
 */
export interface TaskCatalogImportRows {
  input: {
    tenantId: number;
    tenantSlug: string;
    csvText: string;
  };
  output: {
    created?: number | null;
    updated?: number | null;
    errorCount?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowOrder-created".
 */
export interface WorkflowOrderCreated {
  input: {
    orderId: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}